language: node_js

node_js:
  - stable
  - v0.10
  - v0.12
  - v4
  - v5
  - v6
  - v7

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - secure: VJilnnPkpe2sgWHFHZde25Cql9CnEZibvO0o9ESI3WfikO6y8LMPmTGMbRY26rrgzwLR5mqhFJXWSLkx48jq7HETz0TTN8V8frA74kt9kE6sEU/cfM8oJMKJvkRVK3iWU0A/UkMOOaTFPyDuZXwMjaHUMuaV/5bvUpyY1mXnxOs=
    - secure: GmqLaNFF5iD7Nef3RaOXxx5AcU0FiELVmp8Ko5lDpNFzRLnACtBIrweGNxT9kKLk+3t6tLppiuf1P/gXEIaLvSjbIl3EqVWdCoTu5mVozD7Qi3OcrIo4GE89UGPI0ENQeldpIdUNSoZDMj+pKXOev4RWQhHwMdC3XCBKJk0UJ+E=

script:
  - npm run lint
  - npm test

after_script:
  - npm run cover
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
  - cat coverage/lcov.info | node_modules/codeclimate-test-reporter/bin/codeclimate.js
