language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
  - "iojs-v1.0.4"

sudo: false

cache:
  directories:
    - node_modules

script: gulp ci

after_script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage
